title: gaeun's blog
description: >
  welcome
copyright: Untitled
sass:
  sass_dir: assets/sass
url: http://gaeungyeongsul.github.io
disqus_shortname: stratajekylldemo
facebook_username:
twitter_username: "#"
linkedin_username: "#"
instagram_username:
pinterest_username:
flickr_username:
github_username: gaeungyeongsul
feed_icon: rss
email: gaeungyeongsul@gmail.com
gems: [jekyll-paginate]
paginate_path: "/page/:num/"
paginate: 5
