title: gaeun's blog
description: >
  **I am Strat222a**, a super simple
  responsive site template freebie
  crafted by [HTML5 UP]
  **I am Gaeun**
  welcome to my blog.
  (http://html5up.net).
copyright: Untitled
copyright: Untitled
sass:
  sass_dir: assets/sass
url: http://rhdalflrhd.github.io
disqus_shortname: stratajekylldemo
facebook_username:
twitter_username: "#"
linkedin_username: "#"
instagram_username:
pinterest_username:
flickr_username:
github_username: gaeungyeongsul
feed_icon: rss
email: "#"
gems: [jekyll-paginate]
paginate_path: "/page/:num/"
paginate: 5
